### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by odiszapc** [indutny/uv_link_t#2]
Excuse me, are there any docs about how to build uv_link_t on Windows? Thx!

**Comment by indutny** [comment]
Have you tried bundling it with http://gypkg.io/ ?

**Comment by odiszapc** [comment]
Yes. It tells me:

```
C:\projects\uv_link_t-1.0.4>gypkg build uv_link_t.gyp

C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\bin\gypkg:6
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

npm --version `1.3.8`

node --version `v0.10.16`

**Comment by odiszapc** [comment]
I'm not familar with gyp, sorry....

**Comment by indutny** [comment]
@odiszapc which node.js version do you use? The minimum is v4.

**Comment by indutny** [comment]
Oh sorry, I see that you pasted version already. Please consider updating to `v4`.

**Comment by indutny** [comment]
Or better `v8` ;)

**Comment by odiszapc** [comment]
Thanks, let me try this...

**Comment by odiszapc** [comment]
Now output of `gypkg build uv_link_t.gyp` is:

```
C:\projects\uv_link_t-1.0.4>gypkg build uv_link_t.gyp
[==================================================--------------------------------------------------] 0.0s
C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\bin\gypkg:91
      throw err;
      ^
Error: git clone git://github.com/libuv/libuv.git C:\projects\uv_link_t-1.0.4\gypkg_deps\libuv\libuv.git@semver-8fc724d failed
fatal: could not create work tree dir 'C:\projects\uv_link_t-1.0.4\gypkg_deps\libuv\libuv.git@semver-8fc724d'.: No such file or directory

    at stderr (C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\lib\gypkg\server.js:444:25)
    at C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\lib\gypkg\server.js:422:14
    at ChildProcess.git.on (C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\lib\gypkg\server.js:439:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\node_modules\gyp.js\lib\gyp\input.js:2689
      throw e;
      ^

Error: Command failed: gypkg deps "git://github.com/libuv/libuv.git@^1.9.0 => uv.gyp:libuv"

C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\bin\gypkg:91
      throw err;
      ^
Error: git clone git://github.com/libuv/libuv.git C:\projects\uv_link_t-1.0.4\gypkg_deps\libuv\libuv.git@semver-8fc724d failed
fatal: could not create work tree dir 'C:\projects\uv_link_t-1.0.4\gypkg_deps\libuv\libuv.git@semver-8fc724d'.: No such file or directory

    at stderr (C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\lib\gypkg\server.js:444:25)
    at C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\lib\gypkg\server.js:422:14
    at ChildProcess.git.on (C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\lib\gypkg\server.js:439:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

Call to 'gypkg deps "git://github.com/libuv/libuv.git@^1.9.0 => uv.gyp:libuv" failed while in C:\projects\uv_link_t-1.0.4\uv_link_t.gyp while trying to load C:\projects\uv_link_t-1.0.4\uv_link_t.gyp
    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at Input.execSync (C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\node_modules\gyp.js\lib\gyp\input.js:80:23)
    at _loop (C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\node_modules\gyp.js\lib\gyp\input.js:691:26)
    at Input.expandVariables (C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\node_modules\gyp.js\lib\gyp\input.js:781:5)
    at Input.processVariablesAndConditionsInList (C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\node_modules\gyp.js\lib\gyp\input.js:1119:27)
    at C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\node_modules\gyp.js\lib\gyp\input.js:1095:14
    at Array.forEach (native)
    at Input.processVariablesAndConditionsInDict (C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\node_modules\gyp.js\lib\gyp\input.js:1084:24)
    at Input.processVariablesAndConditionsInList (C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\node_modules\gyp.js\lib\gyp\input.js:1117:12)
C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\bin\gypkg:70
      throw err;
      ^

Error: GYP failure
    at ChildProcess.proc.on (C:\Users\Alex\AppData\Roaming\npm\node_modules\gypkg\lib\gypkg\server.js:204:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by odiszapc** [comment]
Does it look like gyp doesn't create some necessary directory?

**Comment by odiszapc** [comment]
I've created the corresponding directory manually: `mkdir -p gypkg_deps\libuv\libuv.git@semver-594cb9f`

I think it's issue, but then I see that uv_link_t tests are not compiling on Windows because of sys/socket.h and unistd.h

I used the following dirty hack
```
#ifdef _WIN32
#include <winsock2.h>
#include <io.h>
#else
#include <sys/socket.h>
#include <unistd.h>
#endif
```

And 
```
#ifndef _WIN32
  CHECK_EQ(socketpair(AF_UNIX, SOCK_STREAM, 0, fds), 0, "socketpair()");
#endif
```

Then build completed successfully.

May be there is a correct way to build uv_link_t under Windows

**Comment by indutny** [comment]
Yeah, the tests are unix-specific at the very moment. I think it may be safe to just `#ifndef _WIN32` them for now.

To be completely honest, I don't have a Windows installation and haven't tested it there.

cc @refack if you are interested :wink:

**Comment by odiszapc** [comment]
I've already fixed that. I can PR if you interested

**Comment by odiszapc** [comment]
PR: https://github.com/indutny/uv_link_t/pull/3
